name: Release Webhook Notification

on:
    release:
        types: [published]

jobs:
    notify-webhook:
        runs-on: ubuntu-latest
        environment: staging
        permissions:
          contents: read

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Send release notification to Strapi
              uses: actions/github-script@v7
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                script: |
                  const tag = context.ref.replace("refs/tags/", "");
                  const { data: release } = await github.rest.repos.getReleaseByTag({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    tag: tag
                  });
                  function cleanChangelog(changelog) {
                    if (!changelog) return '';
                    const lines = changelog.split(/\r?\n/);
                    const result = [];
                    for (const line of lines) {
                      if (line.toLowerCase().includes('new contributors')) break;
                      if (line.toLowerCase().includes('full changelog')) continue;
                      const cleanedLine = line.replace(/by\s+@[\w-]+.*$/i, '').replace(/@\w+/g, '').replace(/\bhttps?:\/\/\S+/gi, '').trim();
                      if (cleanedLine.length > 0) result.push(cleanedLine);
                    }
                    return result.join('\n');
                  }

                  const cleanedBody = cleanChangelog(release.body);
                  const payload = {
                    version: release.tag_name,
                    release_name: release.name,
                    release_url: release.html_url,
                    changelog: cleanedBody || 'No release notes provided',
                    type: 'ENTERPRISE',
                    date: release.published_at
                  };
                  console.log('Payload:', cleanedBody);
              env:
                STRAPI_WEBHOOK_URL: ${{ secrets.STRAPI_WEBHOOK_URL }}
                STRAPI_API_TOKEN: ${{ secrets.STRAPI_API_TOKEN }}