name: Get Release Info
on: [push]

jobs:
  get-release:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest release
        id: latest_release
        uses: actions/github-script@v7
        with:
          script: |
            const { data: release } = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            
            core.setOutput('version', release.tag_name);
            core.setOutput('name', release.name);
            core.setOutput('body', release.body);
            
      - name: Display release info
        run: |
          echo "Version: ${{ steps.latest_release.outputs.version }}"
          echo "Name: ${{ steps.latest_release.outputs.name }}"
          echo "Release Notes:"
          echo "${{ steps.latest_release.outputs.body }}"