name: Clean Release Notes
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name to process (optional - uses latest if not provided)"
        required: false
        type: string

jobs:
  clean-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get release notes and clean them
        id: clean_notes
        uses: actions/github-script@v7
        with:
          script: |
            console.log('Sending release notification to console only...');
            const release = context.payload.release;
            console.log('Release notification triggered!');

            // Clean function to remove "by @user in #1234" from the release body
            function cleanBody(body) {
              return body ? body.replace(/\s+by\s+@\S+\s+in\s+#\d+/g, '') : 'No release notes provided';
            }

            const cleanedBody = cleanBody(release.body);

            console.log('Release Details:', {
              tag: release.tag_name,
              name: release.name,
              url: release.html_url,
              created_at: release.created_at,
              published_at: release.published_at,
              original_body: release.body || 'No release notes provided',
              cleaned_body: cleanedBody
            });

      - name: Display cleaned notes
        run: |
          echo "## Cleaned Release Notes for ${{ steps.clean_notes.outputs.tag_name }}"
          echo "${{ steps.clean_notes.outputs.cleaned_notes }}"
