name: Get Release Info with Error Handling
on: [push]

jobs:
  get-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check for releases and get latest
        id: release_check
        uses: actions/github-script@v7
        with:
          script: |
            try {
              // First, check if any releases exist
              const { data: releases } = await github.rest.repos.listReleases({
                owner: context.repo.owner,
                repo: context.repo.repo,
                per_page: 1
              });
              
              if (releases.length === 0) {
                console.log('No releases found in this repository');
                core.setOutput('has_releases', 'false');
                core.setOutput('version', 'No releases');
                core.setOutput('name', 'No releases found');
                core.setOutput('body', 'This repository has no releases yet');
                return;
              }
              
              // Get the latest release
              const { data: release } = await github.rest.repos.getLatestRelease({
                owner: context.repo.owner,
                repo: context.repo.repo
              });
              
              core.setOutput('has_releases', 'true');
              core.setOutput('version', release.tag_name);
              core.setOutput('name', release.name);
              core.setOutput('body', release.body);
              
            } catch (error) {
              console.log(`Error: ${error.message}`);
              core.setOutput('has_releases', 'false');
              core.setOutput('version', 'Error fetching releases');
              core.setOutput('name', 'Error');
              core.setOutput('body', error.message);
            }
            
      - name: Display results
        run: |
          echo "Has releases: ${{ steps.release_check.outputs.has_releases }}"
          echo "Version: ${{ steps.release_check.outputs.version }}"
          echo "Name: ${{ steps.release_check.outputs.name }}"
          echo "Body: ${{ steps.release_check.outputs.body }}"