name: Clean Release Notes
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name to process (optional - uses latest if not provided)"
        required: false
        type: string

jobs:
  clean-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get release notes and clean them
        id: clean_notes
        uses: actions/github-script@v7
        with:
          script: |
            const { data: releases } = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 1
            });
            
            if (releases.length === 0) {
              console.log('No releases found in this repository');
              core.setOutput('has_releases', 'false');
              core.setOutput('version', 'No releases');
              core.setOutput('name', 'No releases found');
              core.setOutput('body', 'This repository has no releases yet');
              return;
            }
            
            // Get the latest release
            const { data: release } = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            console.log('Sending release notification to console only...');
            console.log('Release notification triggered!');

            function cleanChangelog(changelog) {
              if (!changelog) return '';
              return changelog
                .split(/\r?\n/)
                .map(line => {
                  if (line.toLowerCase().includes('full changelog')) return '';
                  line = line.replace(/by\s+@[\w-]+.*$/i, '');
                  line = line.replace(/@\w+/g, '');
                  line = line.replace(/\bhttps?:\/\/\S*pull\S*/gi, '');
                  return line.trim();
                })
                .filter(line => line.length > 0)
                .join('\n');
            }

            const cleanedBody = cleanChangelog(release.body);

            console.log('Release Details:', {
              tag: release.tag_name,
              name: release.name,
              url: release.html_url,
              created_at: release.created_at,
              published_at: release.published_at,
              original_body: release.body || 'No release notes provided',
              cleaned_body: cleanedBody
            });

      - name: Display cleaned notes
        run: |
          echo "## Cleaned Release Notes for ${{ steps.clean_notes.outputs.tag_name }}"
          echo "${{ steps.clean_notes.outputs.cleaned_notes }}"
